version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - "3306:3306"
  
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: my_new_database
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mysql-database:
  database:
