services:
  postgre:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: my_new_database
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database:
