version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-database:
