version: '3.8'

services:

  web-local:
    build: 
      context: .
      dockerfile: app-local.Dockerfile
    container_name: web-service-local
    volumes:
      - .:/app
    ports:
      - "3256:3256"
    
  nginx:
    image: nginx
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-local
    ports:
      - 8080:4000

